version: "0.0.1"
services:
  server:
    build: .
    depends_on:
      - mongo
    ports:
      - "8080:8080"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
