name: Build Server Docker Image

on:
  push:
    branches:
      - 'server/**'
  pull_request:
    branches:
      - 'main'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        working-directory: ./server
        run: |
          docker build . --file Dockerfile
